### ISSUE TITLE
Screeps+ Grafana (help?)

### ISSUE THREAD

**Issue by Dragonissa** [ScreepsPlus/node-agent#11]
Hey

i was using your Screeps+-Agent for quite a while until my Grafana dashboard, source, etc. was completely wiped. I can still use the .js to push the data to it but the dashboard is gone and i have absolutely no idea how to get it back like it was before.

Cheers

**Comment by AlinaNova21** [comment]
Yea, grafana 4 was swapped for the beta I had up for 5. It was announced in slack last week. Goto https://screepspl.us/grafana4 for access to the old dashboards, please export them from there and import into the new. The grafana4 URL will be removed in the future

**Comment by Dragonissa** [comment]
Thanks a lot. I got it to work again.
