### ISSUE TITLE
getting unauthorized in app

### ISSUE THREAD

**Issue by netnutmike** [ScreepsPlus/node-agent#12]
I noticed the graphs all of a sudden stopped having data.  When I run the node app it comes back unauthorized.  No changes were made.  I did get a new update notice and I did install the update using npm but the problem still exists.

I have verified that the password for screeps is correct and that the token from screepspl.us are the same.

Any thoughts?

**Comment by Dragonissa** [comment]
https://github.com/ScreepsPlus/node-agent/issues/11 Probably the same as mine

**Comment by AlinaNova21** [comment]
Make sure you are using a token for screeps if on official, otherwise it won't work anymore, they removed username/password login support in the API back in February. See the sample config in this repo, it has comments and shows how the config should look.

**Comment by netnutmike** [comment]
I commented out the username and password lines and it gets further now.  Now I am getting: (node:3180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Bad Request

Here is the config (with the tokens stripped out):

```
module.exports = {
       screeps: {
                token: '',
                method: 'memory.stats', // Valid Options: 'console' 'memory.stats'
                shard: ['shard1'],
                connect: {
                        // For Private servers, uncomment the following:
                        // host: 'server1.screepspl.us',
                        // port: 21025,
                        // protocol: 'http'
                }
        },
        service: {
                url: 'https://screepspl.us',
                token: ''      // Token supplied upon account creation
        },
        checkForUpdates: true,
        showRawStats: true // This dumps stats to console on every push if enabled
}
```

**Comment by netnutmike** [comment]
ok, problem solved.  I ended up renaming and re-downloading the source from github.  I was getting errors but then i realized that the version I downloaded is running Node 8 not 6.  After switching to version 8 everything started running again.  Woo Hoo!!!  Thanks!
