### ISSUE TITLE
Doesnt appear to push information to Grafana

### ISSUE THREAD

**Issue by Dragonissa** [ScreepsPlus/node-agent#13]
As the title says, the script doesnt appear to send the data to Grafana. Using the raw data output i can see that it collects them correctly, but doesnt get any respond since "Result: " and the Dashboard is empty.

`         "num_construction_sites": 0,
         "num_my_construction_sites": 0,
         "ground_resources": {},
         "num_source_containers": 0
      }
   },
   "credits": 0,
   "power": 0,
   "leaderboard": {
      "rank": 269,
      "score": 2152544
   }
}
Pushing stats
Result:`

[screeps.txt](https://github.com/ScreepsPlus/node-agent/files/2345518/screeps.txt)

**Comment by AlinaNova21** [comment]
The server was having issues for a few hours. this has been fixed now.

**Comment by Dragonissa** [comment]
oh, thanks for the clarification.
