### ISSUE TITLE
credits renamed to money

### ISSUE THREAD

**Issue by canberranet** [ScreepsPlus/node-agent#4]
let credits = res.body.credits || 0 
should be
let credits = res.body.money || 0 

?

**Comment by canberranet** [comment]
rolled back to a previous version.

**Comment by AlinaNova21** [comment]
Sorry about that, the credits variable exists on the returned object and got mixed up sometime, this is fixed in  cb7988817f9403ac11a0f9a4a3438a23c6fc625b
